name: econ-project-templates-julia
dependencies:
- alabaster=0.7.7=py35_0
- babel=2.2.0=py35_0
- docutils=0.12=py35_0
- jinja2=2.8=py35_0
- markupsafe=0.23=py35_0
- openssl=1.0.2f=0
- pip=8.0.2=py35_0
- pygments=2.1=py35_0
- python=3.5.1=0
- pytz=2015.7=py35_0
- readline=6.2=2
- setuptools=19.6.2=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.3.5=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=1
- pip:
  - latexcodec==1.0.1
  - oset==0.1.3
  - pybtex==0.19
  - pybtex-docutils==0.2.1
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.9
  - sphinxcontrib-bibtex==0.3.3

