dependencies:
- alabaster=0.7.3=py34_0
- babel=1.3=py34_0
- docutils=0.12=py34_0
- freetype=2.5.2=1
- jinja2=2.7.3=py34_1
- libpng=1.5.13=1
- markupsafe=0.23=py34_0
- matplotlib=1.4.3=np19py34_1
- nose=1.3.6=py34_0
- numpy=1.9.2=py34_0
- openssl=1.0.1k=1
- pandas=0.16.1=np19py34_0
- pip=6.1.1=py34_0
- pygments=2.0.2=py34_0
- pyparsing=2.0.3=py34_0
- python=3.4.3=0
- python-dateutil=2.4.2=py34_0
- pytz=2015.4=py34_0
- readline=6.2=2
- setuptools=16.0=py34_0
- six=1.9.0=py34_0
- snowballstemmer=1.2.0=py34_0
- sphinx=1.3.1=py34_0
- sphinx_rtd_theme=0.1.7=py34_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - cloud-sptheme==1.6
  - latexcodec==1.0.1
  - oset==0.1.3
  - pybtex==0.18
  - pybtex-docutils==0.2.1
  - pyyaml==3.11
  - sphinx-rtd-theme==0.1.7
  - sphinxcontrib-bibtex==0.3.2
  - picky

